### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Hamsterman** [homespun/homebridge-platform-snmp#2]
Install failed.
I am using Homebridge for docker (v.1.2.3)

USER: root
DIR: /homebridge
CMD: npm install --save homebridge-platform-snmp@latest

> arp-a@0.5.2 install /homebridge/node_modules/homebridge-platform-snmp/node_modules/homespun-discovery/node_modules/arp-a
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/homebridge-platform-snmp/node_modules/homespun-discovery/node_modules/arp-a/build'
  SOLINK_MODULE(target) Release/obj.target/macos.node
  COPY Release/macos.node
make: Leaving directory '/homebridge/node_modules/homebridge-platform-snmp/node_modules/homespun-discovery/node_modules/arp-a/build'

> pcap@3.1.0 install /homebridge/node_modules/homebridge-platform-snmp/node_modules/pcap
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/homebridge-platform-snmp/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
../pcap_binding.cc:2:10: fatal error: pcap/pcap.h: No such file or directory
    2 | #include <pcap/pcap.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [pcap_binding.target.mk:112: Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory '/homebridge/node_modules/homebridge-platform-snmp/node_modules/pcap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-54-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/homebridge-platform-snmp/node_modules/pcap
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@3.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-28T16_37_59_505Z-debug.log

Command failed. Please review log for details.

**Comment by sparkplug37** [comment]
I'm using Homebridge v 1.2.5 and I too get the same issue as above. I've tried several previous versions of this plugin which all produced the same error so I assume its a change in Homebridge itself causing this issue.
